openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: Simple API for managing products

paths:
  /api/products:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Add a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
              properties:
                name:
                  type: string
                  example: "Dog food"
                price:
                  type: number
                  example: 12.99
      responses:
        '201':
          description: Product created

  /api/products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Update a product by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated product name"
                price:
                  type: number
                  example: 15.99
      responses:
        '200':
          description: Product updated
    delete:
      summary: Delete a product by ID
      responses:
        '200':
          description: Product deleted
